
import type { Metadata } from "next";


import NavBar from "@/app/components/NavBar";
import Footer from "@/app//components/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body
        
      >
        <header>
          <NavBar />
        </header>

        {children}
        <footer>
          {" "}
     
        </footer>
      </body>
    </html>
  );
}
 